
version: "2"

services:
  www:
    build: .
    ports:
      - "71:80"
    volumes:
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      #- ./application:/var/www/html/
    links:
      - db:db
    networks:
      - default
  db:
    image: mysql:5.7.13
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql:rw
      - ./mysql-dump:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    networks:
      - default
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
  redis:
    image: 'redis:latest'
    environment:
    - ALLOW_EMPTY_PASSWORD=yes
    ports:
    - '6389:6379'
    volumes:
    - ./redis_data:/bitnami/redis/data

volumes:
  db_data:
  redis_data:

networks:
  default:
    driver: bridge